name: Test
on:
  workflow_dispatch:

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          brew update
          brew install python3 || : # python doesn't need to be linked
          brew install pkg-config cairo pango libpng jpeg giflib librsvg
          pip install setuptools
      - name: Install
        run: npm install --build-from-source
      - name: Test
        run: npm test
